





select MONHOC.MAMON, MONHOC.TENMON, DETHI.SOLUONGCAUHOI, DETHI.THOIGIANTHI from MONHOC INNER JOIN LOPHP ON LOPHP.MAMON = MONHOC.MAMON INNER JOIN DETHI ON DETHI.MALOPHP = LOPHP.MALOPHP INNER JOIN COSINHVIEN ON COSINHVIEN.MALOPHP = LOPHP.MALOPHP where MSSV = '21004063' AND NGAYTHI like '%2023-06-02%' 

